networks:
  traefik_proxy:
    external: true
  default:

services:
  mysql:
    image: mysql:8.0
    container_name: votapp-db
    environment:
      - MYSQL_ROOT_PASSWORD=6786DA543DFGSdsa
      - MYSQL_TCP_PORT=3306
      - MYSQL_USER=votapp
      - MYSQL_PASSWORD=6786DA543DFGSdsa
      - MYSQL_DATABASE=votapp
      - MYSQL_ROOT_HOST=%
    command: --init-file /home/db.sql
    volumes:
      - ./database/db.sql:/home/db.sql
    restart: unless-stopped
    networks:
      - default

  php:
    build:
       dockerfile: Dockerfile
    container_name: votapp-app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=votapp
      - MYSQL_DBPASS=6786DA543DFGSdsa
      - MYSQL_DBNAME=votapp
    depends_on:
      - mysql
    networks:
      - traefik_proxy
      - default
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=traefik_proxy"
    - "traefik.http.routers.votapp-router.rule=Host(`votapp.samuelelonghin.it`)"
    - "traefik.http.routers.votapp-router.entrypoints=websecure"
    - "traefik.http.routers.votapp-router.tls.certresolver=le"
    - "traefik.http.services.votapp.loadbalancer.server.port=80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: votapp-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: 6786DA543DFGSdsa
    restart: unless-stopped
    
    networks:
      - traefik_proxy
      - default
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=traefik_proxy"
    - "traefik.http.routers.admin-votapp-router.rule=Host(`admin.votapp.samuelelonghin.it`)"
    - "traefik.http.routers.admin-votapp-router.entrypoints=websecure"
    - "traefik.http.routers.admin-votapp-router.tls.certresolver=le"
    - "traefik.http.services.admin-votapp.loadbalancer.server.port=80"
